version: '3.2'

services:

  robotframework-docker:
    build:
      context: ./build
      dockerfile: Dockerfile
      #cache_from: 
      #  -  "${IMAGE_NAME:docker-robot}:latest" 
    image: docker-robot
    #user: "robot"
    volumes:
      - robotframework_data:/usr/src/app
    container_name: docker-robot-v1
    #entrypoint: /docker-entrypoint.sh
    #restart: always
    tty: true

volumes:
  robotframework_data:
    driver: local