version: '2'
services:

  robotframework-mocha:
    build:
      context: ./build/mocha
      dockerfile: Dockerfile
    image: rf-mocha
    #user: "robot"
    volumes:
      - robotframework_data:/usr/src/app
    container_name: robotframework-16.04-01-mocha
    #entrypoint: /docker-entrypoint.sh
    #restart: always
    tty: true

  # robotframework-fedora:
  #   build:
  #     context: ./build/fedora
  #     dockerfile: Dockerfile
  #   image: rf-fedora
  #   #user: "robot"
  #   volumes:
  #     - robotframework_data:/usr/src/app
  #   container_name: robotframework-16.04-01-fedora
  #   #entrypoint: /docker-entrypoint.sh
  #   #restart: always
  #   tty: true

  # robotframework-18.04-01:
  #   build:
  #     context: ./Build/ubuntu-18.04
  #     dockerfile: Dockerfile
  #   image: rf-0000002
  #   user: "robot"
  #   volumes:
  #     - robotframework_data:/usr/src/app
  #   container_name: robotframework-18.04-01
  #   restart: always
  #   tty: true

volumes:
  robotframework_data:
    driver: local