name: Docker Image CI

on:
  push:
    branches: 
      - v1.0.0

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file ./build/mocha/Dockerfile --tag my-image-name:$(date +%s)
  
